# -- display -------------------------------------------------------------------

set -g base-index 1           # start windows numbering at 1
set -g renumber-windows on    # renumber windows when a window is closed

# -- status bar ----------------------------------------------------------------
set-option -g status-style bg=default
set -g window-status-current-style 'bg=green,fg=black'

set-window-option -g status-left "#[fg=black, bg=white] #S "

set -g status-right-style bg=green,fg=black

# -- navigaton between windows -------------------------------------------------
bind Left previous-window
bind Right next-window
